version: '3.8'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server
    hostname: sqlNode1
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"
    networks:
      - mynetwork
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets

networks:
  mynetwork:
  